version: '3.8'

services:
  db:
    platform: linux/amd64
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=SmartHire2026!
      - MSSQL_PID=Developer
    volumes:
      - sqldata:/var/opt/mssql

volumes:
  sqldata: